In [1]:
#Problem - 1: Array Creation:

#1. Initialize an empty array with size 2X2.
import numpy as np

empty_array=np.empty((2,2))
print(empty_array)

[[2.33088727e-086 9.86877513e+044]
 [6.06762498e-154 6.38796479e+029]]


In [7]:
#1 For array filled with zeros
zero_array=np.zeros((2,2))
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [6]:

#2.
array_filled=np.full((2,2),5)
print(array_filled)


[[5 5]
 [5 5]]


In [5]:
#2.
array_filled_float=np.full((3,3),3.14,dtype=float)
print(array_filled_float)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [11]:
#2 Creating 3*3 array filled with 3.14 of type float
array_filled_float=np.full((3,3),3.14,dtype=float)
print(array_filled_float)


[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [15]:
#4 Create a zeros array with the same shape but as floats

original_array = np.array([[1, 2, 3], [4, 5, 6]])
# Create a zeros array with the same shape but as floats
zeros_array_float = np.zeros_like(original_array, dtype=float)
print(zeros_array_float)


[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#5 Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

arry= np.array([[1,2,3],[4,5,6]])

#creating an array of ones with the same shape and type as arry
ones_array= np.ones_like(arry)
print(ones_array)


[[1 1 1]
 [1 1 1]]


In [17]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list=[1,2,3,4]
#covert to a NumPy array
array=np.array(new_list)
print(array)


[1 2 3 4]


In [22]:
#4.1.1 Problem-2:Array Manipulation:Numerical Ranges and Array indexing:

#2 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
array=np.arange(9)
matrix=array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
#3 Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix= np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#4 Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

# Create a random array of size 30
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

# Corrected print statement with a comma
print("Random array:", random_array)
print("Mean of the array:", mean_value)


Random array: [0.31540679 0.9682286  0.70155614 0.50797681 0.5157945  0.2337978
 0.63885464 0.51183237 0.61255113 0.53086739 0.03429741 0.38428973
 0.03770117 0.28777584 0.29486242 0.52239275 0.41992824 0.02059047
 0.8559647  0.28670144 0.65838067 0.26066709 0.68111424 0.25008291
 0.76013705 0.37620082 0.15696248 0.31610942 0.97249725 0.62403363]
Mean of the array: 0.45791853008010897


In [27]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.


# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values in the array
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 array:")
print(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)



Random 10x10 array:
[[0.11313511 0.9840216  0.60712929 0.76480469 0.63605671 0.33992363
  0.61232978 0.4732842  0.14790364 0.7522198 ]
 [0.65924403 0.33550789 0.74721646 0.20280981 0.04074012 0.91414714
  0.5739843  0.72568385 0.30788299 0.73259152]
 [0.48112129 0.23191196 0.94873659 0.85212271 0.72311473 0.98138893
  0.6170821  0.9332191  0.39559472 0.57108636]
 [0.22897643 0.43519841 0.08985273 0.36706209 0.92682407 0.43050535
  0.20433214 0.99231602 0.42268525 0.55548434]
 [0.75543419 0.59688035 0.74308817 0.56730768 0.34852529 0.35824582
  0.19853518 0.94249433 0.29208376 0.48453614]
 [0.58624837 0.76912014 0.6044915  0.45254747 0.18169956 0.64936717
  0.23693627 0.48563776 0.1366159  0.56154509]
 [0.75066308 0.1237035  0.89632369 0.46065622 0.1081071  0.09775523
  0.44508182 0.95401775 0.70158041 0.216749  ]
 [0.66593062 0.47531766 0.12104604 0.29768304 0.04595552 0.36740402
  0.77200915 0.84327808 0.64136353 0.85102746]
 [0.88506176 0.65052359 0.88787079 0.6873367  0.10576068 0.6

In [28]:
#6Create a zero array of size 10 and replace 5th element with 1.

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print("Updated array:", zero_array)


Updated array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [29]:
#7 Reverse an array arr = [1,2,0,0,4,0]
# Given array
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array using slicing
reversed_arr = arr[::-1]

print("Reversed array:", reversed_arr)




Reversed array: [0, 4, 0, 0, 2, 1]


In [30]:
#8Create a 2d array with 1 on border and 0 inside.

# Create a 2D array of size (5x5) with all ones
array = np.ones((5, 5))

# Set the inner elements (excluding the border) to zero
array[1:-1, 1:-1] = 0

print("2D array with 1 on border and 0 inside:")
print(array)



2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
#9Create a 8X8 matrix and fill it with a checkerboard pattern.

# Create an 8x8 matrix with alternating 1s and 0s (checkerboard pattern)
checkerboard = np.zeros((8, 8))

# Fill the checkerboard pattern with 1s at the appropriate positions
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("8x8 Checkerboard Pattern:")
print(checkerboard)





8x8 Checkerboard Pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [32]:
#PROBLEM 04: MATRIX OPERATIONS
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_result = x + y
print("1. Addition of x and y:")
print(add_result)

subtract_result = x - y
print("\n2. Subtraction of x and y:")
print(subtract_result)

multiply_result = x * 2
print("\n3. Multiplication of x with 2:")
print(multiply_result)

square_result = x ** 2
print("\n4. Square of each element in x:")
print(square_result)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print(f"Dot product of v and w: {dot_vw}")
print("Dot product of x and v:")
print(dot_xv)
print("Dot product of x and y:")
print(dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\n6. Concatenation:")
print("Concatenation of x and y along rows:")
print(concat_xy)
print("Concatenation of v and w along columns:")
print(concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:")
    print(concat_xv)
except ValueError as e:
    print("\n7. Error in concatenating x and v:")
    print(e)
    print("Explanation: This error occurs because the dimensions of x (2x2) and v (1x2) don't match along axis 1.")


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x with 2:
[[ 2  4]
 [ 6 10]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation:
Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

7. Error in concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: This error occurs because the dimensions of x (2x2) and v (1x2) don't match along axis 1.


In [ ]:
#4.2Experiments
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
result_list_add = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(f"Time taken for addition with Python lists: {end - start:.5f} seconds")

start = time.time()
result_array_add = array1 + array2
end = time.time()
print(f"Time taken for addition with NumPy arrays: {end - start:.5f} seconds")

# 2. Element-wise Multiplication
start = time.time()
result_list_mul = [x * y for x, y in zip(list1, list2)]
end = time.time()
print(f"Time taken for multiplication with Python lists: {end - start:.5f} seconds")


start = time.time()
result_array_mul = array1 * array2
end = time.time()
print(f"Time taken for multiplication with NumPy arrays: {end - start:.5f} seconds")

# 3. Dot Product
start = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end = time.time()
print(f"Time taken for dot product with Python lists: {end - start:.5f} seconds")

start = time.time()
dot_product_array = np.dot(array1, array2)
end = time.time()
print(f"Time taken for dot product with NumPy arrays: {end - start:.5f} seconds")

# 4. Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
np_matrix1 = np.array(list_matrix1)
np_matrix2 = np.array(list_matrix2)

start = time.time()
result_matrix_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
end = time.time()
print(f"Time taken for matrix multiplication with Python lists: {end - start:.5f} seconds")


start = time.time()
result_matrix_np = np.dot(np_matrix1, np_matrix2)
end = time.time()
print(f"Time taken for matrix multiplication with NumPy arrays: {end - start:.5f} seconds")



Time taken for addition with Python lists: 0.10603 seconds
Time taken for addition with NumPy arrays: 0.00540 seconds
Time taken for multiplication with Python lists: 0.12345 seconds
Time taken for multiplication with NumPy arrays: 0.00479 seconds
Time taken for dot product with Python lists: 0.16466 seconds
Time taken for dot product with NumPy arrays: 0.00319 seconds
